# FILE:    netlify.toml
# VERSION: v13
# UPDATED: 2026-05-05 02:50
# CHANGES: v13 (CR012 cont): Points to index-v13.html.

[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from   = "/.netlify/functions/*"
  to     = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from   = "/"
  to     = "/index-v13.html"
  status = 200
